export const GET_LISTDATA_REQUEST = "GET_LISTDATA_REQUEST";
export const GET_LISTDATA_SUCCESS = "GET_LISTDATA_SUCCESS";
export const GET_LISTDATA_ERROR = "GET_LISTDATA_ERROR";

export const ADD_ITEMTOCART_REQUEST = "ADD_ITEMTOCART_REQUEST";
export const ADD_ITEMTOCART_SUCCESS = "ADD_ITEMTOCART_SUCCESS";
export const ADD_ITEMTOCART_ERROR = "ADD_ITEMTOCART_ERROR";

export const DELETE_ITEMTOCART_REQUEST = "DELETE_ITEMTOCART_REQUEST";
